name: East River
abreviation: USCOGE
crs:
  epsg: 32613
elevation:
  unit: ft        # source unit for edges
  bins:
    labels: ["<9k", "9k-10k","10k-11k", "11k-12k", ">12k"]
    edges:        # same length = len(labels)+1; -inf/+inf allowed
      - -inf
      - 9000
      - 10000
      - 11000
      - 12000
      - +inf
aso_years:
  start: 2018
  end: 2025
conus404_indexing:
  idy_min: 503
  idy_max: 517
  idx_min: 485
  idx_max: 497
